Ques1 Consider warehouse inventory system. [1D Array]
    1. Create an array consisting of product code & corresponding quantity
    2. Determine the dimension of the inventory array
    3. Given a product code search through the array to find quantity of array
    4. Split the array to 2 arrays 
    5. Reterive the quantity using array index 
    6. Check the shape of the inventory array
    7. reshape the inventory onto 2D array
    8. Create a copy of the inventory array
    9. Add new items to the inventory

In [3]:
# pip install numpy  commnad to install the numpy

import numpy as np
#1 [pro_Code,Quantity]
inventary_arr=np.array([[1,10],[2,20],[3,30],[4,40],[5,50],[6,60]])
print("The product and corresponding quantity are :\n",inventary_arr)

#2 determine the dimension of array
Dimension=inventary_arr.ndim
print("The Dimension of inventary array :",Dimension)
print("\n")

#3 Search quantity with product code
product_code=(6)
Quantity=inventary_arr[inventary_arr[:,0]==product_code,1]
print("The quantity of the given product code ",product_code, ":", Quantity)
print("\n")

#4 Slit the taken array
prod_arr1=inventary_arr[:,0]
quan_arr2=inventary_arr[:,1]
print("The product codes are:",prod_arr1)
print("The quantities are:",quan_arr2)
print("\n")
print("-------sliptted array------")
newarr = np.array_split(inventary_arr, 3)

# print(newarr)
print(newarr[0])
print(newarr[1])
print(newarr[2])
print("\n")

#5 getting the quantity using the array index
index=5
quan_at_index=inventary_arr[index,1]
print("The quantity at index",index,":",quan_at_index )
print("\n")

#6 find the shape
shape=inventary_arr.shape
print("The shape of the inventary is:",shape)
print("\n")

#7 Re-shape
reshape=inventary_arr.reshape(-5,2)
print("The Reshape of the inventary is:\n",reshape)
print("\n")

#8 copy
copy_original_arr=np.copy(inventary_arr)
print("The copy of inventary array is:\n",copy_original_arr)
print("\n")

#9 adding the new item
new_arr=np.array([[7,70],[8,80]])
new_inventary_arr=np.concatenate((inventary_arr,new_arr), axis=0)
print("The after adding Inventary is:\n",new_inventary_arr)

The product and corresponding quantity are :
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]]
The Dimension of inventary array : 2


The quantity of the given product code  6 : [60]


The product codes are: [1 2 3 4 5 6]
The quantities are: [10 20 30 40 50 60]


-------sliptted array------
[[ 1 10]
 [ 2 20]]
[[ 3 30]
 [ 4 40]]
[[ 5 50]
 [ 6 60]]


The quantity at index 5 : 60


The shape of the inventary is: (6, 2)


The Reshape of the inventary is:
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]]


The copy of inventary array is:
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]]


The after adding Inventary is:
 [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]
 [ 6 60]
 [ 7 70]
 [ 8 80]]
